/** Design reminder — Emerald Study House: result evidence leads; score is a calm record, and the next recovery action is unmistakable. */
import { useEffect, useMemo, useState } from "react";
import { BarChart3, BookOpenCheck, CheckCircle2, ChevronRight, ClipboardList, Loader2, ShieldCheck, TriangleAlert } from "lucide-react";
import { useLocation } from "wouter";
import { AppShell } from "@/components/app/AppShell";
import { Button } from "@/components/ui/button";
import { learningUseCases } from "@/application/usecases/LearningUseCases";
import type { AssessmentBlueprint, AssessmentResult, Skill } from "@/domain/learning/types";

const skillDestinations: Record<Skill, string> = { listening: "/skills/listening", speaking: "/skills/speaking", reading: "/skills/reading", writing: "/skills/writing", vocabulary: "/vocabulary", grammar: "/grammar", pronunciation: "/skills/pronunciation", communication: "/skills/communication" };
const skillBangla: Record<Skill, string> = { listening: "Listening", speaking: "Speaking", reading: "Reading", writing: "Writing", vocabulary: "Vocabulary", grammar: "Grammar", pronunciation: "Pronunciation", communication: "Communication" };

export default function AssessmentResultPage() {
  const [location, navigate] = useLocation();
  const resultId = decodeURIComponent(location.replace("/exams/result/", "").split("/")[0]);
  const [result, setResult] = useState<AssessmentResult>();
  const [blueprint, setBlueprint] = useState<AssessmentBlueprint>();
  const [loading, setLoading] = useState(true);
  useEffect(() => { let live = true; void Promise.all([learningUseCases.getAssessmentResults(), learningUseCases.getAssessmentBlueprints()]).then(([results, blueprints]) => { if (!live) return; const found = results.find((item) => item.id === resultId); setResult(found); setBlueprint(blueprints.find((item) => item.id === found?.blueprintId)); }).finally(() => { if (live) setLoading(false); }); return () => { live = false; }; }, [resultId]);
  const recovery = useMemo(() => result?.sectionScores.filter((section) => section.score < 70).sort((a, b) => a.score - b.score) ?? [], [result]);
  if (loading) return <AppShell eyebrow="Assessment record" title="ফলাফল খুলছে"><div className="assessment-state"><Loader2 className="animate-spin" />Local assessment record পড়া হচ্ছে…</div></AppShell>;
  if (!result) return <AppShell eyebrow="Assessment record" title="ফলাফল পাওয়া যায়নি"><section className="assessment-empty paper-card"><ClipboardList size={30} /><h2>এই local resultটি পাওয়া যায়নি</h2><p>সম্ভবত এটি অন্য ডিভাইস বা browser profile-এ সংরক্ষিত ছিল।</p><Button onClick={() => navigate("/history")}>Assessment history দেখো</Button></section></AppShell>;
  return <AppShell eyebrow="Assessment result" title={blueprint?.banglaTitle ?? "Assessment record"}>
      <section className="result-hero paper-card"><div><span className="eyebrow">Stored locally · {new Date(result.completedAt).toLocaleDateString("en-GB")}</span><h2>{result.passed ? "প্রয়োজনীয় evidence পাওয়া গেছে" : "পরের review-এ শক্ত হও"}</h2><p>{result.passed ? "এই assessment-এর configured rule পূরণ হয়েছে। এটি একটি educational learning record; official certification নয়।" : "এই ফলাফল তোমার দুর্বল অংশ চিনতে সাহায্য করবে। ভুলগুলো review করে আবার চেষ্টা করা যাবে।"}</p><div className="result-action-row"><Button onClick={() => navigate("/history")}><BarChart3 size={16} />History ও comparison</Button><Button variant="outline" onClick={() => navigate("/mistakes")}><BookOpenCheck size={16} />Review mistakes</Button>{result.passed && (result.assessmentType === "level" || result.assessmentType === "final") && <Button variant="outline" onClick={() => navigate("/certificates")}><ShieldCheck size={16} />Certificates & badges</Button>}</div></div><div className={result.passed ? "result-score-pass" : "result-score-review"}><strong>{result.score}%</strong><span>{result.earnedPoints}/{result.totalPoints} points</span><small>{result.passed ? "passed this learning check" : "recovery recommended"}</small></div></section>
    <section className="result-section-grid"><article className="paper-card result-breakdown"><header><div><span className="card-kicker"><ClipboardList size={15} />Section breakdown</span><h2>Skill evidence</h2></div><ShieldCheck size={21} /></header>{result.sectionScores.map((section) => <div className="assessment-section-row" key={section.sectionId}><div><strong>{skillBangla[section.skill]}</strong><span>{section.earnedPoints}/{section.totalPoints} points</span></div><div className="assessment-score-track"><i style={{ width: `${Math.max(3, section.score)}%` }} /></div><b>{section.score}%</b></div>)}</article><article className="paper-card result-recovery"><header><div><span className="card-kicker"><TriangleAlert size={15} />Recovery plan</span><h2>পরের কার্যকর পদক্ষেপ</h2></div><ChevronRight size={21} /></header>{recovery.length ? recovery.slice(0, 3).map((section) => <button type="button" key={section.sectionId} onClick={() => navigate(skillDestinations[section.skill])}><span>{skillBangla[section.skill]}</span><small>{section.score}% · focused practice</small><ChevronRight size={16} /></button>) : <div className="result-positive"><CheckCircle2 size={18} /><span>সব measured section configured threshold-এর উপরে আছে। Review queue-তে ভুল থাকলে সেগুলো একবার দেখে নাও।</span></div>}<Button variant="outline" onClick={() => navigate(`/exams/${result.blueprintId}`)}>আবার এই assessment দাও</Button></article></section>
    {(result.manualReviewQuestionIds.length > 0 || result.wrongQuestionIds.length > 0) && <section className="result-review-note"><TriangleAlert size={16} /><span>{result.manualReviewQuestionIds.length ? `${result.manualReviewQuestionIds.length}টি উত্তর manual review বা analysis ছাড়া score হয়নি। ` : ""}{result.wrongQuestionIds.length ? `${result.wrongQuestionIds.length}টি objective item review queue-তে রাখা হয়েছে।` : "সব objective item সঠিক ছিল।"}</span></section>}
  </AppShell>;
}
