/** Design reminder — “Emerald Study House”: the learning path is a calm academic ledger, not a game map. */
import { ArrowRight, CheckCircle2, CircleDotDashed, LockKeyhole, Route } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "wouter";
import { learningUseCases } from "@/application/usecases/LearningUseCases";
import { AppShell } from "@/components/app/AppShell";

type CourseMap = Awaited<ReturnType<typeof learningUseCases.getCourseMap>>;

export default function LearningPathPage() {
  const [courseMap, setCourseMap] = useState<CourseMap>([]);
  useEffect(() => { void learningUseCases.getCourseMap("course-english-foundations").then(setCourseMap); }, []);
  const nextStudy = courseMap.flatMap(({ level, units }) => units.map((unit) => ({ level, unit }))).find(({ level, unit }) => level.availability !== "coming-soon" && unit.unlocked && !unit.completed);
  return <AppShell eyebrow="CEFR learning path" title="তোমার শেখার পথ"><section className="learning-path-hero paper-card"><div><p className="card-kicker">A structured route from Pre-A1 to C2</p><h2>এক ধাপ করে,<br /><em>ব্যবহারযোগ্য ইংরেজি।</em></h2><p>প্রতিটি CEFR level-এ স্পষ্ট লক্ষ্য, ছোট unit এবং প্রয়োজনমতো review আছে।</p></div><Route size={40} aria-hidden="true" /></section><section className="cefr-ribbon" aria-label="CEFR level ribbon">{courseMap.map(({ level, unlocked, completed }) => { const open = unlocked && level.availability !== "coming-soon"; const status = completed ? "complete" : open ? "current" : "future"; const content = <><strong>{level.code}</strong><small>{completed ? "Complete" : open ? "Available" : "Future"}</small></>; return open ? <Link key={level.id} href={`/learn/level/${level.code}`} className={`cefr-ribbon-segment cefr-ribbon-${status}`}>{content}</Link> : <div key={level.id} className={`cefr-ribbon-segment cefr-ribbon-${status}`}>{content}</div>; })}</section>{nextStudy && <section className="study-next-action"><div><p className="card-kicker">Next study action</p><h2>{nextStudy.unit.unit.title}</h2><p>{nextStudy.unit.unit.objective ?? nextStudy.unit.unit.summary}</p></div><Link className="lesson-link" href={`/unit/${nextStudy.unit.unit.id}`}>এখন শুরু করি <ArrowRight size={16} /></Link></section>}<section className="learning-ledger-heading"><div><p className="card-kicker">Learning ledger</p><h2>CEFR level অনুযায়ী তোমার পাঠ</h2></div><span>{courseMap.length}টি ধাপ</span></section><section className="cefr-path-list" aria-label="CEFR learning path">{courseMap.map(({ level, units, unlocked, completed }) => <article className={`cefr-path-card ${unlocked ? "is-open" : "is-locked"} ${completed ? "is-complete" : ""}`} key={level.id}><div className="cefr-path-marker">{completed ? <CheckCircle2 /> : unlocked ? <CircleDotDashed /> : <LockKeyhole />}</div><div className="cefr-path-copy"><p>{level.code} · {level.availability === "coming-soon" ? "Coming next" : completed ? "Completed" : unlocked ? "Available now" : "Locked"}</p><h2>{level.title}</h2><span>{level.objective ?? level.summary}</span><small>{units.length} learning unit{units.length === 1 ? "" : "s"}</small></div>{unlocked && level.availability !== "coming-soon" ? <Link className="lesson-link" href={`/learn/level/${level.code}`}>Level খুলুন <ArrowRight size={16} /></Link> : <span className="locked-note">আগের ধাপ শেষ হলে খুলবে</span>}</article>)}</section></AppShell>;
}
