/** Design reminder — “Emerald Study House”: the resource reader feels like a calm bilingual field note, with evidence and practice cues rather than dense textbook pages. */
import { ArrowLeft, Bookmark, BookOpenCheck, CheckCircle2, Clock3, FileText, PenLine, ShieldCheck, VolumeX } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useRoute } from "wouter";
import { learningUseCases } from "@/application/usecases/LearningUseCases";
import { AppShell } from "@/components/app/AppShell";
import type { LibraryResource, PersonalNote } from "@/domain/learning/types";

export default function LibraryResourcePage() {
  const [, params] = useRoute("/library/:resourceId"); const resourceId = params?.resourceId ?? "";
  const [resource, setResource] = useState<LibraryResource>(); const [saved, setSaved] = useState(false); const [note, setNote] = useState<PersonalNote>(); const [noteText, setNoteText] = useState(""); const [related, setRelated] = useState<LibraryResource[]>([]); const [ready, setReady] = useState(false); const [practised, setPractised] = useState(false);
  useEffect(() => { void (async () => { const current = await learningUseCases.getLibraryResource(resourceId); if (!current) { setReady(true); return; } const [state, relatedItems] = await Promise.all([learningUseCases.getLibraryResourceState(resourceId), Promise.all(current.relatedResourceIds.map((id) => learningUseCases.getLibraryResource(id)))]); setResource(current); setSaved(state.saved); setNote(state.note); setNoteText(state.note?.text ?? ""); setRelated(relatedItems.filter((item): item is LibraryResource => Boolean(item))); setReady(true); void learningUseCases.recordLibraryResourceView(resourceId); })(); }, [resourceId]);
  const toggleSaved = async () => setSaved(await learningUseCases.toggleBookmark(resourceId, "library"));
  const saveNote = async () => { await learningUseCases.saveNote(resourceId, noteText.trim()); const latest = await learningUseCases.getNote(resourceId); setNote(latest); };
  const markPractised = async () => { await learningUseCases.recordLibraryResourceView(resourceId, { practicedAt: new Date().toISOString() }); setPractised(true); };
  if (!ready) return <AppShell eyebrow="English Library" title="Reference loading"><div className="library-reader-loading">Local reference note প্রস্তুত হচ্ছে…</div></AppShell>;
  if (!resource) return <AppShell eyebrow="English Library" title="Reference not found"><section className="library-empty"><BookOpenCheck size={24}/><h2>এই reference note পাওয়া যায়নি</h2><Link href="/library">Library-তে ফিরে যান</Link></section></AppShell>;
  return <AppShell eyebrow="English Library · reference note" title={resource.title}>
    <article className="library-reader">
      <Link href="/library" className="library-back-link"><ArrowLeft size={16} /> Library catalogue</Link>
      <header className="library-reader-header"><div><p className="section-kicker">{resource.type.replace(/-/g, " ")} · {resource.level}</p><h2>{resource.title}</h2><h3>{resource.banglaTitle}</h3><p>{resource.banglaSummary}</p><p className="library-reader-summary">{resource.summary}</p><div className="library-reader-ledger"><span>CEFR {resource.level}</span><span><Clock3 size={14}/> {resource.estimatedMinutes} min study note</span><span><ShieldCheck size={14}/> Original · local record</span></div></div><div className="library-reader-actions"><button type="button" onClick={() => void toggleSaved()}><Bookmark size={17} fill={saved ? "currentColor" : "none"}/>{saved ? "Saved locally" : "Save reference"}</button><span><Clock3 size={15}/> প্রায় {resource.estimatedMinutes} মিনিট</span></div></header>
      <div className="library-fact-grid">{resource.facts.map((fact) => <div key={fact.label}><small>{fact.banglaLabel ?? fact.label}</small><strong>{fact.banglaValue ?? fact.value}</strong><span>{fact.value}</span></div>)}</div>
      <div className="library-reading-layout"><div className="library-reading-body">{resource.sections.map((section) => <section className={`library-reference-section tone-${section.tone}`} key={section.id}><p>{section.banglaLabel} <span>{section.label}</span></p><h3>{section.banglaBody ?? section.body}</h3>{section.banglaBody && <div>{section.body}</div>}</section>)}
        {resource.examples.length > 0 && <section className="library-example-block"><p className="section-kicker"><BookOpenCheck size={15}/> উদাহরণে দেখুন</p>{resource.examples.map((example) => <blockquote key={example.english}><strong>{example.english}</strong><span>{example.bangla}</span>{example.note && <small>{example.note}</small>}</blockquote>)}</section>}
        {resource.commonMistakes.length > 0 && <section className="library-mistake-block"><p className="section-kicker"><CheckCircle2 size={15}/> সাধারণ ভুল</p>{resource.commonMistakes.map((mistake) => <div key={mistake.incorrect}><s>{mistake.incorrect}</s><strong>{mistake.corrected}</strong><p>{mistake.banglaExplanation}</p></div>)}</section>}
      </div><aside className="library-reader-side"><section><p className="section-kicker"><PenLine size={14}/> নিজের নোট</p><textarea value={noteText} onChange={(event) => setNoteText(event.target.value)} placeholder="নিজের উদাহরণ বা মনে রাখার সূত্র লিখুন…"/><button type="button" onClick={() => void saveNote()}><FileText size={15}/> {note ? "নোট আপডেট" : "লোকাল নোট রাখুন"}</button></section><section><p className="section-kicker"><CheckCircle2 size={14}/> ব্যবহারের প্রমাণ</p><p>নিয়মটি নিজের একটি বাক্যে ব্যবহার করার পর এই note-টিকে practised হিসেবে চিহ্নিত করুন।</p><button type="button" className={practised ? "is-complete" : ""} onClick={() => void markPractised()}>{practised ? "Practised locally" : "Mark as practised"}</button></section>{resource.audioStatus === "not-included" && <section className="library-audio-note"><VolumeX size={17}/><p><strong>Audio included নয়</strong><span>এই reference note-এ কোনো audio file নেই; ভুলভাবে playback-এর প্রতিশ্রুতি দেওয়া হচ্ছে না।</span></p></section>}</aside></div>
      {related.length > 0 && <section className="library-related"><p className="section-kicker">সম্পর্কিত note</p>{related.map((item) => <Link key={item.id} href={`/library/${item.id}`}><span>{item.banglaTitle}</span><small>{item.title}</small></Link>)}</section>}
      <footer className="library-reader-source"><ShieldCheck size={16}/><span><strong>Source & rights:</strong> {resource.attribution} · {resource.license} · Local reference record</span></footer>
    </article>
  </AppShell>;
}
