/** Design reminder — “ভাষার মানচিত্র”: mistakes are revisit pins, never failure cards. */
/** Design reminder — Emerald Study House: every error is evidence-led and points toward one calm, useful recovery action. */
import { BookOpenCheck, RotateCcw, TriangleAlert } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { learningUseCases } from "@/application/usecases/LearningUseCases";
import { AppShell } from "@/components/app/AppShell";
import { QuestionCard } from "@/components/learning/QuestionCard";
import type { AssessmentQuestion, AssessmentResult, MistakeRecord, Question, SkillError } from "@/domain/learning/types";

type MistakeBundle = { record: MistakeRecord; question?: Question };
export default function MistakeBankPage() {
  const [mistakes, setMistakes] = useState<MistakeBundle[]>([]);
  const [skillErrors, setSkillErrors] = useState<SkillError[]>([]);
  const [assessmentReview, setAssessmentReview] = useState<Array<{ result: AssessmentResult; question: AssessmentQuestion }>>([]);
  const [selectedId, setSelectedId] = useState("");
  const reload = useCallback(async () => { const [next, nextSkillErrors, results, questions] = await Promise.all([learningUseCases.getMistakes(), learningUseCases.getSkillErrors(), learningUseCases.getAssessmentResults(), learningUseCases.getAssessmentQuestions({ approvedOnly: true })]); const byId = new Map(questions.map((question) => [question.id, question])); setAssessmentReview(results.flatMap((result) => result.wrongQuestionIds.map((id) => ({ result, question: byId.get(id) })).filter((item): item is { result: AssessmentResult; question: AssessmentQuestion } => Boolean(item.question)))); setMistakes(next); setSkillErrors(nextSkillErrors); setSelectedId((current) => next.some(({ record }) => record.id === current) ? current : next[0]?.record.id ?? ""); }, []);
  useEffect(() => { void reload(); }, [reload]);
  const active = mistakes.find(({ record }) => record.id === selectedId) ?? mistakes[0];
  return <AppShell eyebrow="Review record" title="Mistake Bank">
    <section className="mistake-intro paper-card"><div><p className="card-kicker"><TriangleAlert size={15} /> ভুল মানেই targeted review</p><h2>যে জায়গায় থেমেছিলে,<br /><em>সেখান থেকেই আবার শুরু।</em></h2><p>Lesson, skill practice ও completed assessment-এর ভুলগুলো local learning record-এ থাকে। Evidence ছাড়া কোনো ভুল দেখানো হয় না।</p></div><strong>{mistakes.length + skillErrors.length + assessmentReview.length}<small>টি active record</small></strong></section>
    <section className="skill-error-sheet paper-card"><header><div><p className="card-kicker">Skill error record</p><h2 className="section-title">Six-skill review queue</h2></div><BookOpenCheck size={21} /></header>{skillErrors.length ? <div className="skill-error-list">{skillErrors.map((error) => <article key={error.id}><span>{error.skill}</span><div><strong>{error.content}</strong><p>{error.explanation}</p><small>{error.frequency} time{error.frequency === 1 ? "" : "s"} · {new Date(error.timestamp).toLocaleDateString("en-GB")}</small></div><a href={`${import.meta.env.BASE_URL}skills/${error.skill}`}>Review</a></article>)}</div> : <p className="skill-error-empty">Skill lab-এ scored activity ভুল হলে সেটি এখানে বিষয়ভিত্তিক review task হিসেবে দেখা যাবে।</p>}</section>
    <section className="skill-error-sheet paper-card"><header><div><p className="card-kicker">Assessment review</p><h2 className="section-title">Completed assessment-এর ভুল</h2></div><BookOpenCheck size={21} /></header>{assessmentReview.length ? <div className="skill-error-list">{assessmentReview.map(({ result, question }) => <article key={`${result.id}-${question.id}`}><span>{question.skill}</span><div><strong>{question.prompt}</strong><p>{question.banglaExplanation ?? question.explanation ?? "Assessment Hub-এ একই topic-এর focused practice করো।"}</p><small>{new Date(result.completedAt).toLocaleDateString("en-GB")} · {result.assessmentType}</small></div><a href={`${import.meta.env.BASE_URL}exams/result/${result.id}`}>Result</a></article>)}</div> : <p className="skill-error-empty">Completed assessment-এ objective ভুল হলে সেটি এখানে review cue হিসেবে দেখা যাবে।</p>}</section>
    {!mistakes.length ? <section className="mistake-empty paper-card"><BookOpenCheck size={28} /><h2>এখন কোনো lesson retry নেই</h2><p>Lesson বা practice-এ ভুল হলে সেটি এখানে ফিরে আসবে।</p></section> : <section className="mistake-layout"><aside className="mistake-list" aria-label="mistakes list">{mistakes.map(({ record, question }, index) => <button type="button" className={record.id === active?.record.id ? "mistake-list-active" : ""} key={record.id} onClick={() => setSelectedId(record.id)}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{question?.prompt ?? "Question unavailable"}</strong><small>{record.reason} · আবার চেষ্টা করো</small></div><RotateCcw size={16} /></button>)}</aside><div className="mistake-retry">{active.question ? <QuestionCard question={active.question} onAnswered={() => void reload()} /> : <p>এই প্রশ্নটি আর পাওয়া যাচ্ছে না।</p>}</div></section>}
  </AppShell>;
}
