/** Design reminder — Emerald Study House: future-facing labs are usable where local capability exists and candid where it does not. */
import { Award, Bot, CalendarDays, ClipboardCheck, FileText, MessageCircleMore, Send, UserRound } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import { AppShell } from "@/components/app/AppShell";
import { RecordingPanel } from "@/components/learning/RecordingPanel";
import { Button } from "@/components/ui/button";

type PrototypeKind = "ai" | "roleplay" | "exams" | "profile" | "history" | "certificates";
const metadata: Record<PrototypeKind, { title: string; eyebrow: string; icon: typeof Bot }> = { ai: { title: "AI Coach", eyebrow: "Guided learning", icon: Bot }, roleplay: { title: "Roleplay Lab", eyebrow: "Speaking practice", icon: MessageCircleMore }, exams: { title: "Exam Center", eyebrow: "Practice format", icon: ClipboardCheck }, profile: { title: "Learner profile", eyebrow: "Account", icon: UserRound }, history: { title: "Learning history", eyebrow: "Records", icon: CalendarDays }, certificates: { title: "Certificates", eyebrow: "Achievement", icon: Award } };
const roleplayCards = ["Ordering tea at a café", "Meeting a new classmate", "Asking for directions"];

export default function PrototypeStudioPage({ kind }: { kind: PrototypeKind }) {
  const meta = metadata[kind]; const Icon = meta.icon;
  const [message, setMessage] = useState(""); const [sent, setSent] = useState(false); const [scenario, setScenario] = useState(roleplayCards[0]);
  return <AppShell eyebrow={meta.eyebrow} title={meta.title}><section className="prototype-hero paper-card"><span className="skill-lab-icon"><Icon size={24} /></span><div><p className="card-kicker">Phase 1 foundation</p><h2>{kind === "ai" ? "A clear place for future guidance" : kind === "roleplay" ? "Practice a real-world conversation" : kind === "exams" ? "Short practice, then a fuller exam format" : kind === "profile" ? "Your local study preferences" : kind === "history" ? "Your activity records will grow here" : "Certificates appear only after real completion rules exist"}</h2><p>এই screenটি কোনো feature simulate করে না। যেখানে real local action আছে, সেটিই এখানে ব্যবহার করা যায়; অন্য অংশগুলো future work হিসেবে চিহ্নিত।</p></div></section>
    {kind === "ai" && <section className="coach-console paper-card"><div className="coach-thread"><p className="coach-bubble coach-bubble-system">AI Coach integration এই phase-এ চালু নেই। তুমি question draft করে রাখতে পারো; পাঠানো message এই device ছাড়বে না।</p>{sent && <p className="coach-bubble coach-bubble-user">{message}</p>} {sent && <p className="coach-bubble coach-bubble-system">Question draft saved in this session. AI response এখনো available নয়।</p>}</div><form onSubmit={(event) => { event.preventDefault(); if (message.trim()) setSent(true); }}><input value={message} onChange={(event) => { setMessage(event.target.value); setSent(false); }} placeholder="Ask about a word or sentence…" aria-label="AI coach message draft"/><Button type="submit" disabled={!message.trim()}><Send size={16} /> Send</Button></form></section>}
    {kind === "roleplay" && <section className="roleplay-layout"><div className="roleplay-cards">{roleplayCards.map((item) => <button key={item} type="button" className={scenario === item ? "roleplay-card roleplay-card-active" : "roleplay-card"} onClick={() => setScenario(item)}><MessageCircleMore size={18} /><strong>{item}</strong><small>Choose scenario</small></button>)}</div><RecordingPanel prompt={`Scenario: ${scenario}. Say one short English sentence to begin.`} /></section>}
    {kind === "exams" && <section className="exam-launcher paper-card"><FileText size={25} /><h2>Current practice session</h2><p>Existing question bank দিয়ে এখনই timed-feeling, filterable practice চালানো যায়। Full mock scoring, reading passages ও exam history পরবর্তী content release-এ যোগ হবে।</p><Link href="/practice/setup"><Button>Open practice setup</Button></Link></section>}
    {kind === "profile" && <section className="skill-placeholder paper-card"><UserRound size={27} /><h2>Local learner profile</h2><p>এই standalone version-এ sign-in নেই। Theme, language mode, motion এবং daily goal Settings-এ এই device-এ সংরক্ষিত থাকে।</p><Link href="/settings"><Button>Open settings</Button></Link></section>}
    {kind === "history" && <section className="skill-placeholder paper-card"><CalendarDays size={27} /><h2>History is building</h2><p>Practice attempts, mistakes, reviews ও writing drafts local storage-এ থাকে। একটি complete history timeline পরবর্তী release-এর জন্য নির্ধারিত।</p><Link href="/progress"><Button>Open progress</Button></Link></section>}
    {kind === "certificates" && <section className="skill-placeholder paper-card"><Award size={27} /><h2>No certificate yet</h2><p>Certificate তৈরি হবে কেবল verified completion rule, course criteria ও export design যোগ হওয়ার পরে। এখন কোনো fake certificate দেখানো হচ্ছে না।</p><Link href="/learn"><Button>Continue learning</Button></Link></section>}</AppShell>;
}
