/** Design reminder — Emerald Study House: a word detail reads like a trustworthy study note with its source visible. */
/* Emerald Study House — English target word leads; Bangla explanation, CEFR context, mastery and provenance form one factual study note. */
import { ArrowLeft, ExternalLink, Volume2 } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useParams } from "wouter";
import { learningUseCases } from "@/application/usecases/LearningUseCases";
import { AppShell } from "@/components/app/AppShell";
import { Button } from "@/components/ui/button";

type Detail = Awaited<ReturnType<typeof learningUseCases.getVocabularyDetail>>;
const stateLabel = { new: "নতুন", learning: "শেখা চলছে", familiar: "পরিচিত", strong: "ভালো", mastered: "আয়ত্ত" };

export default function VocabularyDetailPage() {
  const { word } = useParams<{ word: string }>(); const [detail, setDetail] = useState<Detail | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { setLoading(true); void learningUseCases.searchVocabulary({ query: decodeURIComponent(word ?? ""), pageSize: 8 }).then(async (result) => { const exact = result.entries.find((entry) => entry.item.word.toLocaleLowerCase("en-US") === decodeURIComponent(word ?? "").toLocaleLowerCase("en-US")); setDetail(exact ? await learningUseCases.getVocabularyDetail(exact.item.id) : null); setLoading(false); }); }, [word]);
  const item = detail?.item; const say = () => { if (item && "speechSynthesis" in window) { window.speechSynthesis.cancel(); window.speechSynthesis.speak(new SpeechSynthesisUtterance(item.word)); } };
  if (!item) return <AppShell eyebrow="Vocabulary" title="Word note"><section className="skill-placeholder paper-card"><h2>{loading ? "Word note খোলা হচ্ছে" : "Word পাওয়া যায়নি"}</h2><p>{loading ? "Offline catalogue-এ খোঁজা হচ্ছে।" : "এই নামে কোনো vocabulary record নেই।"}</p><Link href="/vocabulary"><Button variant="outline"><ArrowLeft size={16} /> Vocabulary library</Button></Link></section></AppShell>;
  const mastery = detail.srsCard?.masteryState ?? "new";
  return <AppShell eyebrow={`${item.level} · ${item.partOfSpeech}`} title={item.word}><article className="word-detail paper-card"><div className="word-detail-heading"><div><span>{item.ipa || item.pronunciation}</span><h2>{item.meaning}</h2><small className={`mastery-pill mastery-${mastery}`}>{stateLabel[mastery]}</small></div><Button type="button" variant="outline" onClick={say}><Volume2 size={16} /> Listen</Button></div><p className="word-definition">{item.definition}</p><blockquote>“{item.example}”</blockquote><aside className="word-study-ledger" aria-label="Word study status"><span><b>CEFR context</b>{item.level} · {item.partOfSpeech}</span><span><b>Study status</b>{stateLabel[mastery]}</span><span><b>Next action</b>Listen, then write one sentence</span></aside><div className="word-detail-grid"><div><small>Synonyms</small><p>{item.synonyms.join(", ") || "—"}</p></div><div><small>Antonyms</small><p>{item.antonyms.join(", ") || "—"}</p></div><div><small>Collocations</small><p>{item.collocations.join(", ") || "—"}</p></div><div><small>Frequency rank</small><p>{item.frequencyRank ? `#${item.frequencyRank}` : "Sample record"}</p></div></div>{item.wordFamily?.length ? <section className="word-detail-section"><h3>Word family</h3><div>{item.wordFamily.map((member) => <span key={member.word}>{member.word} · {member.meaning}</span>)}</div></section> : null}{item.phrasalVerbs?.length ? <section className="word-detail-section"><h3>Phrasal verbs</h3>{item.phrasalVerbs.map((phrase) => <p key={phrase.phrase}><strong>{phrase.phrase}</strong> — {phrase.meaning}{phrase.example ? ` · ${phrase.example}` : ""}</p>)}</section> : null}{item.idioms?.length ? <section className="word-detail-section"><h3>Related idioms</h3>{item.idioms.map((idiom) => <p key={idiom.phrase}><strong>{idiom.phrase}</strong> — {idiom.meaning}</p>)}</section> : null}{detail.sentences.length ? <section className="word-detail-section"><h3>Example corpus</h3>{detail.sentences.map((sentence) => <blockquote key={sentence.id}>“{sentence.text}” {sentence.banglaTranslation ? <small>{sentence.banglaTranslation}</small> : null}</blockquote>)}</section> : null}<footer className="source-attribution"><div><small>Source & licence</small><p>{detail.source?.attribution || item.attribution || "Source metadata unavailable"}</p><span>{item.license || "—"} · commercial use {item.commercialUseAllowed ? "permitted" : "not confirmed"}</span></div>{detail.source?.url ? <a href={detail.source.url} target="_blank" rel="noreferrer">Source record <ExternalLink size={14} /></a> : null}</footer><Link href="/vocabulary"><Button variant="outline"><ArrowLeft size={16} /> Back to library</Button></Link></article></AppShell>;
}
