/** Application layer: presentation code calls these use cases, never IndexedDB/repositories directly. */
import { learningRepository } from "@/data/repositories/LearningRepository";

export const learningUseCases = {
  initialize: () => learningRepository.seedIfNeeded(),
  getRoadmap: () => learningRepository.getRoadmap(),
  getCourseMap: (courseId: string) => learningRepository.getCourseMap(courseId),
  getUnit: (unitId: string) => learningRepository.getUnitBundle(unitId),
  getLesson: (lessonId: string) => learningRepository.getLessonBundle(lessonId),
  getContinueLearning: () => learningRepository.getContinueLearning(),
  getLearningSummary: () => learningRepository.getLearningSummary(),
  getVocabulary: () => learningRepository.getVocabulary(),
  getVocabularyEntries: () => learningRepository.getVocabularyEntries(),
  searchVocabulary: (filters?: Parameters<typeof learningRepository.searchVocabulary>[0]) => learningRepository.searchVocabulary(filters),
  getVocabularyDetail: (vocabularyId: string) => learningRepository.getVocabularyDetail(vocabularyId),
  getVocabularyReviewQueue: () => learningRepository.getVocabularyReviewQueue(),
  getSrsCard: (vocabularyId: string) => learningRepository.getSrsCard(vocabularyId),
  updateVocabularyMastery: (vocabularyId: string, state: Parameters<typeof learningRepository.updateVocabularyMastery>[1]) => learningRepository.updateVocabularyMastery(vocabularyId, state),
  importVocabularyBatch: (data: unknown) => learningRepository.importVocabularyBatch(data),
  getGrammarTopics: () => learningRepository.getGrammarTopics(),
  getGrammarConcepts: (filters?: Parameters<typeof learningRepository.getGrammarConcepts>[0]) => learningRepository.getGrammarConcepts(filters),
  getGrammarConcept: (conceptId: string) => learningRepository.getGrammarConcept(conceptId),
  importGrammarBatch: (concepts: Parameters<typeof learningRepository.importGrammarBatch>[0]) => learningRepository.importGrammarBatch(concepts),
  getPracticeQuestions: (filters: { skill?: "grammar" | "vocabulary"; difficulty?: number; count: number }) => learningRepository.getPracticeQuestions(filters),
  getDueReviews: () => learningRepository.getDueReviewItems(),
  getMistakes: () => learningRepository.getMistakes(),
  getProgressSnapshot: () => learningRepository.getProgressSnapshot(),
  getSettings: () => learningRepository.getSettings(),
  updateSettings: (patch: Parameters<typeof learningRepository.updateSettings>[0]) => learningRepository.updateSettings(patch),
  recordFlashcardReview: (vocabularyId: string, rating: "again" | "hard" | "good" | "easy") => learningRepository.recordFlashcardReview(vocabularyId, rating),
  getWritingDraft: (promptId: string) => learningRepository.getWritingDraft(promptId),
  saveWritingDraft: (promptId: string, text: string, submitted?: boolean) => learningRepository.saveWritingDraft(promptId, text, submitted),
  submitAnswer: (questionId: string, userAnswer: string) => learningRepository.recordAnswer(questionId, userAnswer),
  recordActivity: (lessonId: string, blockId: string, response?: string, score?: number, confidence?: Parameters<typeof learningRepository.recordActivity>[4]) => learningRepository.recordActivity(lessonId, blockId, response, score, confidence),
  toggleBookmark: (contentId: string, contentType: Parameters<typeof learningRepository.toggleBookmark>[1]) => learningRepository.toggleBookmark(contentId, contentType),
  saveNote: (contentId: string, text: string) => learningRepository.saveNote(contentId, text),
  importCurriculum: (data: unknown) => learningRepository.importCurriculum(data),
  exportUserData: () => learningRepository.exportUserData(),
  importUserData: (data: unknown) => learningRepository.importUserData(data),
  resetUserData: () => learningRepository.resetUserData(),
};
